### ISSUE TITLE
RazorViewEngine doesn't support C# 6?

### ISSUE THREAD

**Issue by tompazourek** [StackExchange/StackExchange.Precompilation#4]
You mention to use `RoslynRazorViewEngine` instead of `RazorViewEngine`, because `RazorViewEngine` doesn't support C# 6.

I use `RazorViewEngine` with C# 6 support in my project successfully. Was the support for C# 6 already implemented in some version? What am I missing?

**Comment by m0sa** [comment]
I guess you added C# support via the [Microsoft.CodeDom.Providers.DotNetCompilerPlatform](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform) package. In order to deploy this to a server you need to allow your asp.net worker process to execute the roslyn `csc.exe` which is copied to your `/bin` folder. Our SREs weren't exactly thrilled by this idea. The `RoslynRazorViewEngine` does everything in memory. If you wan't to do meta-programming on the generated view code, you need to precompile them, and use the `PrecompiledViewEngine` anyway.

**Comment by tompazourek** [comment]
You're right, thanks for the insights.

I am using the `RazorViewEngine` only in debug mode for development purposes, similarly as your **Test.WebApp** uses `RoslynRazorViewEngine`.

In release mode, I switch to `PrecompiledViewEngine` using the preprocessor directives, which means that I should get the same output for production.
