### ISSUE TITLE
MsBuild injection point conflicts with OctoPack

### ISSUE THREAD

**Issue by scottt732** [StackExchange/StackExchange.Precompilation#9]
I have a project which is deployed via Octopus Deploy.  Looking through the build logs it appears that the Octopack is building it's package earlier in the pipeline than StackExchange.Precompilation.Build.targets.  It looks like you are using BuildDependsOn where they are using CompileDependsOn.  I'm not sure if that's the cause.  As a result, while we are pre-compiling our views during build, they aren't making it to our deployment targets.

**Comment by m0sa** [comment]
Hey. Never dealt with OctoPack before, but thanks for reporting this, since we're planing to look at OctoPack internally as well!

Actually, [OctoPack.targets](https://github.com/OctopusDeploy/OctoPack/blob/3.4.1/source/tools/OctoPack.targets#L6) hooks into `BuildDependsOn` as well, and SE.Precompilation hooks into `CompileDependsOn`. The thing is, that `BuildDependsOn` depends on `CompileDependsOn` via [`CoreBuild` -> `CoreBuildDependsOn`](http://referencesource.microsoft.com/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/bin_/amd64/Microsoft.Common.CurrentVersion.targets,750). So, assuming all the precompilation properties are set correctly it should work (`SEPrecompilerSkip = false`, `SEPrecompilerIncludeRazor = true`). My guess would be that the later is `false`, due to a different command / msbuild target you're running on the build server vs. locally.

I wonder how you run octopus deploy (on your build server, from msbuild, do you invoke the task directly or indirectly). A msbuild command like with args would be super useful, and an [structured log of the same command](https://github.com/KirillOsenkov/MSBuildStructuredLog) would be even more useful.

**Comment by m0sa** [comment]
@scottt732 any updates on this?

**Comment by scottt732** [comment]
Hey.  Would you mind if I e-mailed this to you or would you mind describing what you're looking for.     I go by my username at gmail.

**Comment by scottt732** [comment]
Apologies.  Configuration/RTFM issue on my part.  Thank you for your time and for helping me get this resolved.

**Comment by m0sa** [comment]
np, glad I could help
